# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0002_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.CharField(max_length=250),
        ),
    ]
