# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0003_auto_20160510_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mod_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
