# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0004_auto_20160511_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url_code',
            field=models.CharField(max_length=7),
        ),
    ]
