# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0008_auto_20160511_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mod_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
