# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0009_auto_20160511_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
