# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0010_area_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
