# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0011_auto_20160514_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(),
        ),
    ]
