# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0014_auto_20160514_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Customer',
        ),
    ]
