# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0019_auto_20160514_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
